name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install gettext libgtk2.0-dev libgconf2-dev

      - name: Check out Classpath
        uses: actions/checkout@v4

      - name: Build GNU Classpath
        run: |
          javac -version
          ./autogen.sh
          ./configure \
            --disable-plugin \
            --disable-examples \
            --disable-tools \
            --disable-gjdoc
          make && sudo make install

      - name: Check out JamVM
        uses: actions/checkout@v4
        with:
          repository: ingelabs/jamvm
          path: jamvm

      - name: Build JamVM
        run: |
          cd jamvm
          export JAVA_HOME=$JAVA_HOME_8_X64
          export PATH=$JAVA_HOME/bin:$PATH
          ./autogen.sh
          ./configure
          make && sudo make install      

      - name: Check out Malva
        uses: actions/checkout@v4
        with:
          repository: ingelabs/malva
          path: malva

      - name: Build Malva and run tests
        run: |
          cd malva
          export JAVA_HOME=$JAVA_HOME_8_X64
          export PATH=$JAVA_HOME/bin:$PATH
          JAVA=/usr/local/jamvm/bin/jamvm make check

