name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: ingelabs/jamvm

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java 8
        run: |
          export JAVA_HOME=$JAVA_HOME_8_X64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install gettext libgtk2.0-dev libgconf2-dev

      - name: Build GNU Classpath
        run: |
          ./autogen.sh
          ./configure \
            --disable-plugin \
            --disable-examples \
            --disable-tools \
            --disable-gjdoc
          make && sudo make install

      - name: Build JamVM
        run: |
          java -version
          export JAVA_HOME=$JAVA_HOME_8_X64
          export PATH=$JAVA_HOME/bin:$PATH        
          java -version
          ./autogen.sh
          ./configure
          make && sudo make install      

      - name: Check out Malva
        uses: actions/checkout@v3
        with:
          repository: ingelabs/malva
          path: malva

      - name: Run tests
        run: |
          cd malva
          JAVA=jamvm make check

